name: Lab2 Data Pipeline - Processing

on:
  push:
    branches:
      - Lab2
  workflow_dispatch:

jobs:
  data_processing:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Cleaning and Standardization Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }} 
          SHEET_ID: '1yAadaH9J2lHvn8sbO33jqia4opqYYAHZ1sR7yevztKQ' 
        run: python data_processor.py

      - name: Display Report Content
        run: |
          echo "--- DATA PROCESSING REPORT ---"
          cat report.txt